### ISSUE TITLE
Implement a 3D visualisation of a rover's position in space

### ISSUE THREAD

**Issue by griggle** [Amazing-Group-D-Lego-Robot/Digital-Twin-Rover#7]
Maybe add debug information to the visualisation too (sensor values, fps, etc...)

**Comment by grinchios** [comment]
- [ ] Add all incoming data from world state to left side
- [ ] Time stamps and latency
- [ ] Parse any data from twin dynamically
- [ ] Think of a better way to show sensors on the visualisation, lines from sensor locations?
